---
# #############################################################################
# ###   Ansible variables defaults                                          ###
# #############################################################################
ansible_user: ubuntu
git_username: Ubuntu Focal
git_email: ubuntu@email.com