#cloud-config
merge_how:
  - name: list
    settings: [append]
  - name: dict
    settings: [no_replace, recurse_list]

autoinstall:
  #### Host and account setup.
  # Autoinstall only allows for one initial user, but user-data might be used
  # to setup multiple users (prefer to use Ansible for this).
  identity:
    hostname: ${OS_HOSTNAME}
    username: ${USER0_USERNAME}
    realname: ${USER0_REALNAME}
    password: ${USER0_PW_CRYPTED}
