#cloud-config
merge_how:
  - name: list
    settings: [append]
  - name: dict
    settings: [recurse_array]

autoinstall:

  # early-commands:

  late-commands:
    # To save some hassle pass the Ansible folder into the target system.
    # Otherwise you either need to either passthrough a thumb drive with the
    # repository or download it.
    # https://refspecs.linuxfoundation.org/FHS_2.3/fhs-2.3.html#USRLOCALSHARE1
    - cp -r /cdrom/autoinstall/ansible /target/usr/local/share/
    - cp /cdrom/autoinstall/pyproject.toml /target/usr/local/share/
