# =============================================================================
# Install Duplicati
# -----------------------------------------------------------------------------

---
- hosts: lat7490
  connection: local
  become_user: root

  vars:
    # https://docs.ansible.com/ansible/latest/inventory/implicit_localhost.html
    # If this is not set, Ansible might use /usr/bin/python and then might not
    # find certain libraries (ModuleNotFoundError), as described here:
    # https://stackoverflow.com/a/51973504
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    # Define own variables.
    user: "{{ ansible_env.USER }}"
    home_dir: "{{ ansible_env.HOME }}"

  pre_tasks:
    - name: Update apt cache if needed
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 3600



  tasks:
    ##### Duplicati backup.
    # https://duplicati.readthedocs.io/en/latest/02-installation/
    - name: Install prerequisites for duplicati (mono)
      become: true
      ansible.builtin.apt_key:
        keyserver: keyserver.ubuntu.com
        id: 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF

    - name: Enable auto-updating using the system's package manager for mono
      become: true
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.mono-project.com/repo/ubuntu stable-focal main
        state: present
        filename: mono-official-stable

    - name: Install mono and other prerequisites for duplicati
      become: true
      apt:
        pkg:
          - mono-devel
          - gtk-sharp2
          - libappindicator0.1-cil
          - libmono-2.0-1
          - apt-transport-https
          - nano
          - git-core
          - software-properties-common
          - dirmngr
        state: latest
        update_cache: yes

    ##### Download duplicati deb
    # Not idempotent.
    - name: Download docker installer
      become: true
      apt:
        deb: https://updates.duplicati.com/beta/duplicati_2.0.6.3-1_all.deb

    - name: Set Duplicati DAEMON_OPTS
      become: true
      ansible.builtin.lineinfile:
        dest: /etc/default/duplicati
        regexp: '^DAEMON_OPTS='
        line: 'DAEMON_OPTS="--webservice-interface=any --webservice-port=8200 --portable-mode"'
        state: present

    - name: Start and enable Duplicati service
      become: true
      systemd:
        name: duplicati
        state: started
        enabled: yes
        daemon-reload: yes
