---
# #############################################################################
# ###   Ansible variables for Debian                                        ###
# #############################################################################
ansible_user: debian
ansible_connection: ssh
ansible_port: 2222

become_user: root

ansible_ssh_private_key_file: ~/.ssh/id_rsa_ansible

git_username: Debian Bullseye
git_email: debian@email.com