---
#####   Google Chrome   #######################################################
# TODO: somehow there still ends up an apt-repository without `signed-by`
#       in google-chrome.list.
- name: Install Chrome apt repository and signing key (add apt signing key to keyring file)
  become: true
  ansible.builtin.apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    keyring: /etc/apt/trusted.gpg.d/google-chrome.gpg

- name: Enable auto-updating Chrome using the system's package manager
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google-chrome

- name: Install Google Chrome
  become: true
  apt:
    pkg:
      - google-chrome-stable
    state: latest
    update_cache: yes

#####   VS Code   #############################################################
- name: Install VS code apt repository and signing key (add apt signing key to keyring file)
  become: true
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    keyring: /etc/apt/trusted.gpg.d/packages.microsoft.gpg

- name: Enable auto-updating VS code using the system's package manager
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main
    state: present
    filename: vscode

- name: Install VS code
  become: true
  apt:
    pkg:
      - apt-transport-https
      - code
    state: latest
    update_cache: yes

- name: Check installed VS code extensions
  command:
    cmd: code --list-extensions
  register: vs_code_extensions_installed

# VS code recommends to install extensions per user.
- name: Install VS code extensions
  command:
    cmd: "code --install-extension {{ item }}"
  loop: "{{ vs_code_extensions_to_install }}"
  when: item not in vs_code_extensions_installed.stdout

#####   Inkscape   ############################################################
# Installing the latest inkscape version using their ppa.
# https://wiki.inkscape.org/wiki/Installing_Inkscape#Ubuntu_Linux_New_Stable_Versions
- name: Add stable Inkscape ppa
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:inkscape.dev/stable
    update_cache: yes

- name: Install Inkscape
  become: true
  apt:
    pkg:
      - inkscape
    state: latest

#####   Gimp   ################################################################
- name: Add stable Gimp ppa
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:ubuntuhandbook1/gimp
    update_cache: yes

- name: Install Gimp
  become: true
  apt:
    pkg:
      - gimp
      - gimp-gmic
    state: latest

#####   Duplicati backup   ####################################################
# https://duplicati.readthedocs.io/en/latest/02-installation/
- name: Install prerequisites for duplicati (mono)
  become: true
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF

- name: Enable auto-updating using the system's package manager for mono
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.mono-project.com/repo/ubuntu stable-focal main
    state: present
    filename: mono-official-stable

- name: Install mono and other prerequisites for duplicati
  become: true
  apt:
    pkg:
      - mono-devel
      - gtk-sharp2
      - libappindicator0.1-cil
      - libmono-2.0-1
      - apt-transport-https
      - nano
      - git-core
      - software-properties-common
      - dirmngr
    state: latest
    update_cache: yes

##### Download duplicati deb
- name: Download Duplicati installer
  become: true
  apt:
    deb: https://updates.duplicati.com/beta/duplicati_2.0.6.3-1_all.deb

- name: Set Duplicati DAEMON_OPTS
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/default/duplicati
    regexp: '^DAEMON_OPTS='
    line: 'DAEMON_OPTS="--webservice-interface=any --webservice-port=8200 --portable-mode"'
    state: present

- name: Start and enable Duplicati service
  become: true
  systemd:
    name: duplicati
    state: started
    enabled: yes
    daemon-reload: yes
